app:
  env:  "development"
  port: 1323
  debug: true

mongodb:
  connection: "mongodb://172.17.0.1:27017"
  collection: "REIT_DEV"

elasticsearch:
  connection: "http://172.17.0.1:9200"
  indexName: "reitapp"

facebook:
  redirectURL: "https://reit-api.odds.team/Auth/FacebookCallback"
  clientID: "385086385375815"
  clientSecret: "baa3dce5c60b202469c4387f0b588766"
  accesstokenURL: "https://graph.facebook.com/me?fields=email,id,name,first_name,last_name,middle_name,picture&access_token="
  #  scope: []string{"id","name","first_name","last_name","middle_name","picture"}

google:
  redirectURL: "https://reit-api.odds.team/Auth/GoogleCallback"
  clientID: "727520883795-jgv79pgu957lu3oojf8cv30akgbeep7j.apps.googleusercontent.com"
  clientSecret: "C5Y7I3MYKuVoaNBczMn8qoub"
  accesstokenURL: "https://www.googleapis.com/oauth2/v2/userinfo?access_token="
  #  scope: []string{"https://www.googleapis.com/auth/userinfo.profile","https://www.googleapis.com/auth/userinfo.email"}

log:
  level: "debug"
  format: "json"